---
# Fulcio
fulcio:
  config:
    contents: {
      "OIDCIssuers": {
       "https://my-supervisor.demo.pinniped.dev": {
       "IssuerURL": "https://my-supervisor.demo.pinniped.dev",
       "ClientID": "pinniped-cli",
       "SubjectDomain": "https://dev-elnuuoy6.us.auth0.com",
       "Type": "uri"
      },
      },
      "MetaIssuers": {
        "https://kubernetes.*.svc": {
          "ClientID": "sigstore",
          "Type": "kubernetes"
        }
      }
    }
  enabled: true
  namespace:
    name: fulcio-system
    create: true
  forceNamespace: fulcio-system
  server:
    fullnameOverride: fulcio-server
  createcerts:
    fullnameOverride: fulcio-createcerts
  ctlog:
    enabled: false
  server:
    image:
      registry: hectorj2f
      repository: fulcio-bd4d600f674b081a535a886a15cb8d9a
      version: sha256:60626eaec9b3e026a67a892344ad94164055bdbbbc60f0d2e1863d4ebe192574
    ingress:
      hostname: fulcio.localhost
# CTLog
ctlog:
  enabled: true
  namespace:
    name: ctlog-system
    create: true
  forceNamespace: ctlog-system
  fullnameOverride: ctlog
  createcerts:
    fullnameOverride: ctlog-createcerts
  createtree:
    fullnameOverride: ctlog-createtree
# Rekor
rekor:
  enabled: true
  namespace:
    name: rekor-system
    create: true
  forceNamespace: rekor-system
  fullnameOverride: rekor
  server:
    fullnameOverride: rekor-server
  redis:
    fullnameOverride: rekor-redis
  trillian:
    enabled: false
  server:
    ingress:
      hostname: rekor.localhost    
# Trillian
trillian:
  enabled: true
  namespace:
    name: trillian-system
    create: true
  forceNamespace: trillian-system
  fullnameOverride: trillian
  logServer:
    name: trillian-logserver
    fullnameOverride: trillian-logserver
    portHTTP: 8090
    portRPC: 8091
  logSigner:
    name: trillian-logsigner
    fullnameOverride: trillian-logsigner
  mysql:
    fullnameOverride: trillian-mysql
